// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpbgzczhgwiplojqsaiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wYmd6Y3poZ3dpcGxvanFzYWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NTczMTgsImV4cCI6MjA5MTAzMzMxOH0.lu8NqnXwhtlLZXUu5x7TwfqLQv7QjMVh7c1dEX5Pu6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});